name: unlv_ceao_mobile_sign_in
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  firebase_core: ^1.19.1
  cloud_firestore: ^3.2.1
  firebase_storage: ^10.3.1
  firebase_auth: ^3.4.1
  font_awesome_flutter: ^10.1.0
  material_design_icons_flutter: ^5.0.6996
  velocity_x: ^3.5.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  assets:
    - images/


  uses-material-design: true

